services:
  - type: web
    name: cleaning-validation-api
    runtime: python
    repo: https://github.com/DMRX123/cleaning-validation-backend
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port \
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.rjmaczgskjvqcrvkdumr:YOUR_SUPABASE_PASSWORD@aws-0.ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO
