services:
  - type: web
    name: cleaning-validation-api
    runtime: python
    repo: https://github.com/DMRX123/cleaning-validation-backend
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://cleaning_validation_db_user:Rvy2FS9PK54pacbayVMSTB8CXlDfXrb8@dpg-d81eh5dckfvc738c379g-a.oregon-postgres.render.com/cleaning_validation_db?sslmode=require
      - key: SECRET_KEY
        value: "aQJMCZkA92ivP7uYGwgztoFxLEDfRbjs"
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: INFO
      - key: ALLOW_ALL_ORIGINS
        value: "true"